# Data Cleaning

In [1]:
import os

import pandas as pd

ROOT_PATH = os.path.dirname(os.getcwd())
DATA_FOLDER_PATH = os.path.join(ROOT_PATH, 'data', 'raw')

## Import

In [2]:
df = pd.read_parquet(os.path.join(DATA_FOLDER_PATH, "raw_arrivals.parquet"))

df.head()

  access_route     state origin_country    month  year  arrival_count
0        Aérea  Amazonas  África do Sul  janeiro  1989            9.0
1        Aérea  Amazonas         Angola  janeiro  1989            0.0
2        Aérea  Amazonas        Nigéria  janeiro  1989            0.0
3        Aérea  Amazonas  Outros países  janeiro  1989            0.0
4        Aérea  Amazonas     Costa Rica  janeiro  1989            6.0

## Consistency

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 978472 entries, 0 to 978471
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   access_route    978472 non-null  str
 1   state           978472 non-null  str
 2   origin_country  978472 non-null  str
 3   month           978472 non-null  str
 4   year            978472 non-null  int64
 5   arrival_count   968620 non-null  float64
dtypes: float64(1), int64(1), str(4)
memory usage: 78.5 MB

### Checking NaNs

In [4]:
df.isna().mean()

access_route      0.000000
state             0.000000
origin_country    0.000000
month             0.000000
year              0.000000
arrival_count     0.010069
dtype: float64

In [5]:
df[df['arrival_count'].isna()].head()

,access_route,state,origin_country,month,year,arrival_count
16464,Fluvial,Mato Grosso do Sul,África do Sul,janeiro,1989,NaN
16465,Fluvial,Mato Grosso do Sul,Angola,janeiro,1989,NaN
16466,Fluvial,Mato Grosso do Sul,Nigéria,janeiro,1989,NaN
16467,Fluvial,Mato Grosso do Sul,Outros países,janeiro,1989,NaN
16468,Fluvial,Mato Grosso do Sul,Costa Rica,janeiro,1989,NaN

In [6]:
df = df.dropna(subset=['arrival_count'])

## Cleaning

### Date field

In [7]:
df['year'] = df['year'].astype(str)

In [8]:
MONTH_NAME_MAPPING = {
    'janeiro': 'Janeiro',
    'fevereiro': 'Fevereiro',
    'março': 'Março',
    'marco': 'Março',
    'mar�o': 'Março',
    'abril': 'Abril',
    'maio': 'Maio',
    'junho': 'Junho',
    'julho': 'Julho',
    'agosto': 'Agosto',
    'setembro': 'Setembro',
    'outubro': 'Outubro',
    'novembro': 'Novembro',
    'dezembro': 'Dezembro'
}

MONTH_NUM_MAPPING = {
    'janeiro': '01',
    'fevereiro': '02',
    'março': '03',
    'abril': '04',
    'maio': '05',
    'junho': '06',
    'julho': '07',
    'agosto': '08',
    'setembro': '09',
    'outubro': '10',
    'novembro': '11',
    'dezembro': '12'
}

df['month'] = df['month'].str.lower().map(MONTH_NAME_MAPPING)
df['month_num'] = df['month'].str.lower().map(MONTH_NUM_MAPPING)

In [9]:
df['month'].unique()

<ArrowStringArray>
[  'Janeiro', 'Fevereiro',     'Março',     'Abril',      'Maio',     'Junho',
     'Julho',    'Agosto',  'Setembro',   'Outubro',  'Novembro',  'Dezembro']
Length: 12, dtype: str

In [10]:
df['month_num'].unique()

<ArrowStringArray>
['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
Length: 12, dtype: str

In [11]:
df['date'] = pd.to_datetime(df['year'] + '-' + df['month_num'] + '-01')

In [12]:
df['date'].isna().sum()

np.int64(0)

### Access Route field

In [13]:
df['access_route'].unique()

<ArrowStringArray>
[    'Aérea', 'Terrestre',   'Fluvial',  'Marítima',     'Aéreo',  'Marítimo',
     'A�rea',  'Mar�tima']
Length: 8, dtype: str