# Train Test Validation Split

In [1]:
import os

import pandas as pd

ROOT_PATH = os.path.dirname(os.getcwd())
DATA_FOLDER_PATH = os.path.join(ROOT_PATH, 'data', 'processed')

In [2]:
df = pd.read_parquet(os.path.join(DATA_FOLDER_PATH, 'cleaned_arrivals.parquet'))

df.head()

,access_route,state,origin_country,month,year,arrival_count,month_num,date,year_month,state_region,country_cultural_subdivision
0,Aérea,Amazonas,África do Sul,Janeiro,1989,9.0,01,1989-01-31,1989-01-31,Região Norte,Sub-Saharan Africa
1,Aérea,Amazonas,Angola,Janeiro,1989,0.0,01,1989-01-31,1989-01-31,Região Norte,Sub-Saharan Africa
2,Aérea,Amazonas,Nigéria,Janeiro,1989,0.0,01,1989-01-31,1989-01-31,Região Norte,Sub-Saharan Africa
3,Aérea,Amazonas,Outros países,Janeiro,1989,0.0,01,1989-01-31,1989-01-31,Região Norte,Outros
4,Aérea,Amazonas,Costa Rica,Janeiro,1989,6.0,01,1989-01-31,1989-01-31,Região Norte,LATAM

## Split by Time

In [3]:
print(
    f'Complete time range: {df["date"].min().strftime("%d %B %Y")} to {df["date"].max().strftime("%d %B %Y")}'
)

Complete time range: 31 January 1989 to 31 December 2025

In [4]:
train_df = df[df['date'] < '2025-01-31']
print(
    f'Train set time range: {train_df["date"].min().strftime("%d %B %Y")} to {train_df["date"].max().strftime("%d %B %Y")}'
)
train_df.tail()

Train set time range: 31 January 1989 to 31 December 2024

,access_route,state,origin_country,month,year,arrival_count,month_num,date,year_month,state_region,country_cultural_subdivision
943815,Fluvial,Rio Grande do Sul,Suíça,Dezembro,2024,3.0,12,2024-12-31,2024-12-31,Região Sul,Western / Eastern Europe
943816,Fluvial,Rio Grande do Sul,Uruguai,Dezembro,2024,6.0,12,2024-12-31,2024-12-31,Região Sul,LATAM
943817,Fluvial,Santa Catarina,Argentina,Dezembro,2024,120.0,12,2024-12-31,2024-12-31,Região Sul,LATAM
943818,Fluvial,Santa Catarina,Chile,Dezembro,2024,3.0,12,2024-12-31,2024-12-31,Região Sul,LATAM
943819,Fluvial,Santa Catarina,Uruguai,Dezembro,2024,1.0,12,2024-12-31,2024-12-31,Região Sul,LATAM

In [5]:
test_df = df[(df['date'] >= '2025-01-31') & (df['date'] < '2025-07-31')]
print(
    f'Test set time range: {test_df["date"].min().strftime("%d %B %Y")} to {test_df["date"].max().strftime("%d %B %Y")}'
)
test_df.tail()

Test set time range: 31 January 2025 to 30 June 2025

,access_route,state,origin_country,month,year,arrival_count,month_num,date,year_month,state_region,country_cultural_subdivision
956375,Aérea,Santa Catarina,Índia,Junho,2025,2.0,06,2025-06-30,2025-06-30,Região Sul,APAC
956376,Aérea,Distrito Federal,Índia,Junho,2025,14.0,06,2025-06-30,2025-06-30,Região Centro-Oeste,APAC
956377,Terrestre,Paraná,Índia,Junho,2025,8.0,06,2025-06-30,2025-06-30,Região Sul,APAC
956378,Terrestre,Paraná,Índia,Junho,2025,17.0,06,2025-06-30,2025-06-30,Região Sul,APAC
956379,Marítima,Rio Grande do Sul,Índia,Junho,2025,1.0,06,2025-06-30,2025-06-30,Região Sul,APAC

In [6]:
val_df = df[df['date'] >= '2025-07-31']
print(
    f'Validation set time range: {val_df["date"].min().strftime("%d %B %Y")} to {val_df["date"].max().strftime("%d %B %Y")}'
)
val_df.tail()

Validation set time range: 31 July 2025 to 31 December 2025

,access_route,state,origin_country,month,year,arrival_count,month_num,date,year_month,state_region,country_cultural_subdivision
968615,Terrestre,Rio Grande do Sul,Índia,Dezembro,2025,5.0,12,2025-12-31,2025-12-31,Região Sul,APAC
968616,Marítima,Alagoas,Índia,Dezembro,2025,3.0,12,2025-12-31,2025-12-31,Região Nordeste,APAC
968617,Marítima,Santa Catarina,Índia,Dezembro,2025,3.0,12,2025-12-31,2025-12-31,Região Sul,APAC
968618,Marítima,Santa Catarina,Índia,Dezembro,2025,5.0,12,2025-12-31,2025-12-31,Região Sul,APAC
968619,Fluvial,Amapá,Índia,Dezembro,2025,2.0,12,2025-12-31,2025-12-31,Região Norte,APAC

## Output

In [7]:
train_df.to_parquet(os.path.join(DATA_FOLDER_PATH, 'train.parquet'), index=False)
test_df.to_parquet(os.path.join(DATA_FOLDER_PATH, 'test.parquet'), index=False)
val_df.to_parquet(os.path.join(DATA_FOLDER_PATH, 'val.parquet'), index=False)