# Divisão Treino/Teste

In [1]:
import os

import pandas as pd

ROOT_PATH = os.path.dirname(os.getcwd())
DATA_FOLDER_PATH = os.path.join(ROOT_PATH, 'data', 'processed')

In [2]:
df = pd.read_parquet(os.path.join(DATA_FOLDER_PATH, 'cleaned_arrivals_ptbr.parquet'))

df.head()

,access_route,state,origin_country,month,year,arrival_count,month_num,date,year_month,state_region,country_cultural_subdivision
0,Aérea,Amazonas,África do Sul,Janeiro,1989,9.0,01,1989-01-31,1989-01-31,Região Norte,África Subsaariana
1,Aérea,Amazonas,Angola,Janeiro,1989,0.0,01,1989-01-31,1989-01-31,Região Norte,África Subsaariana
2,Aérea,Amazonas,Nigéria,Janeiro,1989,0.0,01,1989-01-31,1989-01-31,Região Norte,África Subsaariana
3,Aérea,Amazonas,Outros países,Janeiro,1989,0.0,01,1989-01-31,1989-01-31,Região Norte,Outros
4,Aérea,Amazonas,Costa Rica,Janeiro,1989,6.0,01,1989-01-31,1989-01-31,Região Norte,LATAM

## Divisão por Tempo

In [3]:
print(
    f'Período completo: {df["date"].min().strftime("%d %B %Y")} a {df["date"].max().strftime("%d %B %Y")}'
)

Período completo: 31 January 1989 a 31 December 2025

In [4]:
# Dados até dezembro de 2024 para treinamento
train_df = df[df['date'] < '2025-01-31']
print(
    f'Período do conjunto de treino: {train_df["date"].min().strftime("%d %B %Y")} a {train_df["date"].max().strftime("%d %B %Y")}'
)
train_df.tail()

Período do conjunto de treino: 31 January 1989 a 31 December 2024

,access_route,state,origin_country,month,year,arrival_count,month_num,date,year_month,state_region,country_cultural_subdivision
943815,Fluvial,Rio Grande do Sul,Suíça,Dezembro,2024,3.0,12,2024-12-31,2024-12-31,Região Sul,Europa Ocidental / Oriental
943816,Fluvial,Rio Grande do Sul,Uruguai,Dezembro,2024,6.0,12,2024-12-31,2024-12-31,Região Sul,LATAM
943817,Fluvial,Santa Catarina,Argentina,Dezembro,2024,120.0,12,2024-12-31,2024-12-31,Região Sul,LATAM
943818,Fluvial,Santa Catarina,Chile,Dezembro,2024,3.0,12,2024-12-31,2024-12-31,Região Sul,LATAM
943819,Fluvial,Santa Catarina,Uruguai,Dezembro,2024,1.0,12,2024-12-31,2024-12-31,Região Sul,LATAM

In [5]:
# Dados de 2025 em diante para teste
test_df = df[df['date'] >= '2025-01-31']
print(
    f'Período do conjunto de teste: {test_df["date"].min().strftime("%d %B %Y")} a {test_df["date"].max().strftime("%d %B %Y")}'
)
test_df.tail()

Período do conjunto de teste: 31 January 2025 a 31 December 2025

,access_route,state,origin_country,month,year,arrival_count,month_num,date,year_month,state_region,country_cultural_subdivision
968615,Terrestre,Rio Grande do Sul,Índia,Dezembro,2025,5.0,12,2025-12-31,2025-12-31,Região Sul,APAC
968616,Marítima,Alagoas,Índia,Dezembro,2025,3.0,12,2025-12-31,2025-12-31,Região Nordeste,APAC
968617,Marítima,Santa Catarina,Índia,Dezembro,2025,3.0,12,2025-12-31,2025-12-31,Região Sul,APAC
968618,Marítima,Santa Catarina,Índia,Dezembro,2025,5.0,12,2025-12-31,2025-12-31,Região Sul,APAC
968619,Fluvial,Amapá,Índia,Dezembro,2025,2.0,12,2025-12-31,2025-12-31,Região Norte,APAC

## Saída

In [6]:
train_df.to_parquet(os.path.join(DATA_FOLDER_PATH, 'train_ptbr.parquet'), index=False)
test_df.to_parquet(os.path.join(DATA_FOLDER_PATH, 'test_ptbr.parquet'), index=False)